# version format
version: 1.0.{build}.0

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

# environment variables
environment:
  SignTool: C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe
  KeyFile: C:\projects\qif2json\qif2json.pfx
  Qif2JsonSnkPath: C:\projects\qif2json\qif2json.snk
  # this is how to set encrypted variable. Go to "Encrypt data" page in account menu to encrypt data.
  CertPassword:
    secure: QDWBD+3IIAYVFCfHFY7YCw==
  PfxUri:
    secure: 96Uy0sDkAp6sTkaD5MptudqaMXrjJkaBQhghxNHvaP9vHbUOcF1R9h9k3LXG6ZnwvJe7+ifJ5IqCV7hkdkSzqKcKkuWllqmNDvO5PK+KTTP/2wks9LCpMBSMnIHFnvB/
  SnkUri:
    secure: 96Uy0sDkAp6sTkaD5MptudqaMXrjJkaBQhghxNHvaP9vHbUOcF1R9h9k3LXG6ZnwWkZOmP1fCRP5m2Bclrbc22uOBlleZWaxVycTis9Jb4QCSI2FFddeTQAxehQypUsI

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

install:
    - cmd: nuget restore
    - ps:  if($env:PfxUri) { Start-FileDownload $env:PfxUri -FileName $env:KeyFile }
    - ps:  if($env:SnkUri) { Start-FileDownload $env:SnkUri -FileName $env:Qif2JsonSnkPath }
    

platform: Any CPU

configuration: Release

before_build:
   -cmd: msbuild WiX.msbuild /p:Version=%APPVEYOR_BUILD_VERSION%

build:
    project: qif2json.sln

test:
  assemblies:
    - qif2json.tests.dll

artifacts:
  - path: qif2json.setup.bootstrap\bin\$(configuration)\*.exe

